# Generated by Django 4.0.1 on 2022-01-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lessonitem_problem"),
        ("problems", "0002_alter_submit_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="submit",
            name="lesson_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.lessonitem",
                verbose_name="časť lekcie",
            ),
        ),
    ]
