# Generated by Django 4.2.1 on 2023-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_submit_lesson_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="testovac_id",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="ID úlohy pre testovač"
            ),
        ),
    ]
