# Generated by Django 4.2.1 on 2023-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_alter_problem_testovac_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="detail_visible",
            field=models.BooleanField(
                default=False, verbose_name="viditeľnosť detailov testovania"
            ),
        ),
    ]
