# Generated by Django 4.2.1 on 2023-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_problem_detail_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="názov")),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tagy",
            },
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.ManyToManyField(to="problems.tag"),
        ),
    ]
