# Generated by Django 4.2.1 on 2023-07-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0006_tag_problem_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "easy"),
                    ("medium", "medium"),
                    ("hard", "hard"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                verbose_name="obtiažnosť",
            ),
        ),
    ]
