# Generated by Django 5.2.1 on 2025-05-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0008_remove_problem_testovac_id_remove_submit_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submit",
            name="language",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="detail_visible",
        ),
        migrations.AlterField(
            model_name="problem",
            name="slug",
            field=models.SlugField(max_length=64, unique=True, verbose_name="slug"),
        ),
    ]
