# Generated by Django 5.2.15 on 2026-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0009_remove_submit_language_alter_problem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("basics", "základy"),
                    ("easy", "ľahká"),
                    ("medium", "stredná"),
                    ("hard", "ťažká"),
                    ("very-hard", "veľmi ťažká"),
                    ("unknown", "neznáma"),
                ],
                default="unknown",
                verbose_name="obtiažnosť",
            ),
        ),
    ]
