# Generated by Django 4.0 on 2021-12-28 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("content", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "učebný text",
                "verbose_name_plural": "učebné texty",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.CreateModel(
            name="LessonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("slug", models.SlugField(max_length=64)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
                (
                    "lesson_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.lessonmaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "časť lekcie",
                "verbose_name_plural": "časti lekcie",
            },
        ),
        migrations.AddConstraint(
            model_name="lessonitem",
            constraint=models.UniqueConstraint(
                fields=("lesson", "order"), name="unique_lesson_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonitem",
            constraint=models.UniqueConstraint(
                fields=("lesson", "slug"), name="unique_lesson_slug"
            ),
        ),
    ]
