# Generated by Django 4.0 on 2021-12-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0001_initial"),
        ("courses", "0002_lessonmaterial_alter_course_slug_alter_lesson_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonitem",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="problems.problem",
            ),
        ),
    ]
