# Generated by Django 4.0.1 on 2022-01-24 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_lessonitem_problem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursegroup",
            options={
                "ordering": ["order"],
                "verbose_name": "skupina kurzov",
                "verbose_name_plural": "skupiny kurzov",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["layer", "order"],
                "verbose_name": "lekcia",
                "verbose_name_plural": "lekcie",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonitem",
            options={
                "ordering": ["order"],
                "verbose_name": "časť lekcie",
                "verbose_name_plural": "časti lekcie",
            },
        ),
    ]
