# Generated by Django 4.0.1 on 2022-01-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_coursegroup_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonmaterial",
            name="material_id",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
    ]
