# Generated by Django 4.0.1 on 2022-01-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_tracker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursegroup",
            options={
                "ordering": ["order"],
                "verbose_name": "skupina kurzov",
                "verbose_name_plural": "skupiny kurzov",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["layer", "order"],
                "verbose_name": "lekcia",
                "verbose_name_plural": "lekcie",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonitem",
            options={
                "ordering": ["order"],
                "verbose_name": "časť lekcie",
                "verbose_name_plural": "časti lekcie",
            },
        ),
        migrations.AddConstraint(
            model_name="tracker",
            constraint=models.UniqueConstraint(
                fields=("lesson_item", "user"), name="unique_item_user"
            ),
        ),
    ]
