# Generated by Django 4.0.2 on 2023-05-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_course_options_course_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="recommended_courses",
            field=models.ManyToManyField(blank=True, to="courses.Course"),
        ),
    ]
