# Generated by Django 4.2.3 on 2023-07-14 11:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "classrooms",
            "0002_alter_classroom_options_alter_classroomuser_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="classroomuser",
            unique_together={("classroom", "user")},
        ),
    ]
