# Generated by Django 4.2.1 on 2023-07-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trojsten_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
