# Generated by Django 5.2.1 on 2025-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_trojsten_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trojsten_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
